# Sport.create(sport_type: '野球')
# Sport.create(sport_type: 'サッカー')
# Sport.create(sport_type: 'ラグビー')
# Sport.create(sport_type: '水泳')
# Sport.create(sport_type: '卓球')
# Sport.create(sport_type: '柔道')
# Sport.create(sport_type: '陸上')

# Grade.create(grade_type: '中学')
# Grade.create(grade_type: '高校')
# Grade.create(grade_type: '大学')
# Grade.create(grade_type: '社会人')

# Position.create(position: '選手')
# Position.create(position: 'コーチ')
# Position.create(position: 'マネージャー')
# Position.create(position: '監督')